name: SistemasUTP
on: 
  push:
    branches: 
      - main

jobs:
  FTP-Deploy-Action: 
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2.0
      with: 
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with: 
        ftp-server: ${{ secrets.SISTEMAS }}
        ftp-username: ${{ secrets.SISTEMAS }}
        ftp-password: ${{ secrets.SISTEMAS }}
